# fly.toml app configuration file generated for composer-sh on 2024-08-17T00:07:53+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'composer-sh'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
